# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Jun  1 23:35:59 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(859, 483)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.deviceComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceComboBox.sizePolicy().hasHeightForWidth())
        self.deviceComboBox.setSizePolicy(sizePolicy)
        self.deviceComboBox.setObjectName(_fromUtf8("deviceComboBox"))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.deviceComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.deviceComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.eyeBlinkSensitivity = QtGui.QLineEdit(self.centralwidget)
        self.eyeBlinkSensitivity.setObjectName(_fromUtf8("eyeBlinkSensitivity"))
        self.horizontalLayout_2.addWidget(self.eyeBlinkSensitivity)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lowerEyeBlinkFrequency = QtGui.QLineEdit(self.centralwidget)
        self.lowerEyeBlinkFrequency.setObjectName(_fromUtf8("lowerEyeBlinkFrequency"))
        self.horizontalLayout_2.addWidget(self.lowerEyeBlinkFrequency)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.higherEyeBlinkFrequency = QtGui.QLineEdit(self.centralwidget)
        self.higherEyeBlinkFrequency.setObjectName(_fromUtf8("higherEyeBlinkFrequency"))
        self.horizontalLayout_2.addWidget(self.higherEyeBlinkFrequency)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rescanMidiButton = QtGui.QPushButton(self.centralwidget)
        self.rescanMidiButton.setObjectName(_fromUtf8("rescanMidiButton"))
        self.horizontalLayout_3.addWidget(self.rescanMidiButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.midiDevice2ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice2ComboBox.setObjectName(_fromUtf8("midiDevice2ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice2ComboBox, 1, 8, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.midiDevice3ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice3ComboBox.setObjectName(_fromUtf8("midiDevice3ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice3ComboBox, 1, 11, 1, 1)
        self.midiDevice0ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice0ComboBox.setObjectName(_fromUtf8("midiDevice0ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice0ComboBox, 1, 2, 1, 1)
        self.midiDevice7ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice7ComboBox.setObjectName(_fromUtf8("midiDevice7ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice7ComboBox, 2, 11, 1, 1)
        self.midiDevice6ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice6ComboBox.setObjectName(_fromUtf8("midiDevice6ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice6ComboBox, 2, 8, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.midiDevice8ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice8ComboBox.setObjectName(_fromUtf8("midiDevice8ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice8ComboBox, 3, 2, 1, 1)
        self.midiDevice4ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice4ComboBox.setObjectName(_fromUtf8("midiDevice4ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice4ComboBox, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 3, 1, 1)
        self.midiDevice5ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice5ComboBox.setObjectName(_fromUtf8("midiDevice5ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice5ComboBox, 2, 5, 1, 1)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 4, 6, 1, 1)
        self.midiDevice14ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice14ComboBox.setObjectName(_fromUtf8("midiDevice14ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice14ComboBox, 4, 8, 1, 1)
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 4, 9, 1, 1)
        self.midiDevice15ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice15ComboBox.setObjectName(_fromUtf8("midiDevice15ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice15ComboBox, 4, 11, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 3, 1, 1)
        self.midiDevice9ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice9ComboBox.setObjectName(_fromUtf8("midiDevice9ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice9ComboBox, 3, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 3, 6, 1, 1)
        self.midiDevice10ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice10ComboBox.setObjectName(_fromUtf8("midiDevice10ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice10ComboBox, 3, 8, 1, 1)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 3, 9, 1, 1)
        self.midiDevice11ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice11ComboBox.setObjectName(_fromUtf8("midiDevice11ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice11ComboBox, 3, 11, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.midiDevice12ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice12ComboBox.setObjectName(_fromUtf8("midiDevice12ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice12ComboBox, 4, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 3, 1, 1)
        self.midiDevice13ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice13ComboBox.setObjectName(_fromUtf8("midiDevice13ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice13ComboBox, 4, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 2, 9, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 9, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 6, 1, 1)
        self.midiDevice1ComboBox = QtGui.QComboBox(self.centralwidget)
        self.midiDevice1ComboBox.setObjectName(_fromUtf8("midiDevice1ComboBox"))
        self.gridLayout_2.addWidget(self.midiDevice1ComboBox, 1, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 2, 6, 1, 1)
        self.resetChannel4Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel4Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel4Button.setObjectName(_fromUtf8("resetChannel4Button"))
        self.gridLayout_2.addWidget(self.resetChannel4Button, 2, 1, 1, 1)
        self.resetChannel8Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel8Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel8Button.setObjectName(_fromUtf8("resetChannel8Button"))
        self.gridLayout_2.addWidget(self.resetChannel8Button, 3, 1, 1, 1)
        self.resetChannel12Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel12Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel12Button.setObjectName(_fromUtf8("resetChannel12Button"))
        self.gridLayout_2.addWidget(self.resetChannel12Button, 4, 1, 1, 1)
        self.resetChannel0Button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetChannel0Button.sizePolicy().hasHeightForWidth())
        self.resetChannel0Button.setSizePolicy(sizePolicy)
        self.resetChannel0Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel0Button.setObjectName(_fromUtf8("resetChannel0Button"))
        self.gridLayout_2.addWidget(self.resetChannel0Button, 1, 1, 1, 1)
        self.resetChannel1Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel1Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel1Button.setObjectName(_fromUtf8("resetChannel1Button"))
        self.gridLayout_2.addWidget(self.resetChannel1Button, 1, 4, 1, 1)
        self.resetChannel5Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel5Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel5Button.setObjectName(_fromUtf8("resetChannel5Button"))
        self.gridLayout_2.addWidget(self.resetChannel5Button, 2, 4, 1, 1)
        self.resetChannel9Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel9Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel9Button.setObjectName(_fromUtf8("resetChannel9Button"))
        self.gridLayout_2.addWidget(self.resetChannel9Button, 3, 4, 1, 1)
        self.resetChannel13Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel13Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel13Button.setObjectName(_fromUtf8("resetChannel13Button"))
        self.gridLayout_2.addWidget(self.resetChannel13Button, 4, 4, 1, 1)
        self.resetChannel2Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel2Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel2Button.setObjectName(_fromUtf8("resetChannel2Button"))
        self.gridLayout_2.addWidget(self.resetChannel2Button, 1, 7, 1, 1)
        self.resetChannel6Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel6Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel6Button.setObjectName(_fromUtf8("resetChannel6Button"))
        self.gridLayout_2.addWidget(self.resetChannel6Button, 2, 7, 1, 1)
        self.resetChannel10Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel10Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel10Button.setObjectName(_fromUtf8("resetChannel10Button"))
        self.gridLayout_2.addWidget(self.resetChannel10Button, 3, 7, 1, 1)
        self.resetChannel14Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel14Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel14Button.setObjectName(_fromUtf8("resetChannel14Button"))
        self.gridLayout_2.addWidget(self.resetChannel14Button, 4, 7, 1, 1)
        self.resetChannel3Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel3Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel3Button.setObjectName(_fromUtf8("resetChannel3Button"))
        self.gridLayout_2.addWidget(self.resetChannel3Button, 1, 10, 1, 1)
        self.resetChannel7Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel7Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel7Button.setObjectName(_fromUtf8("resetChannel7Button"))
        self.gridLayout_2.addWidget(self.resetChannel7Button, 2, 10, 1, 1)
        self.resetChannel11Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel11Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel11Button.setObjectName(_fromUtf8("resetChannel11Button"))
        self.gridLayout_2.addWidget(self.resetChannel11Button, 3, 10, 1, 1)
        self.resetChannel15Button = QtGui.QPushButton(self.centralwidget)
        self.resetChannel15Button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetChannel15Button.setObjectName(_fromUtf8("resetChannel15Button"))
        self.gridLayout_2.addWidget(self.resetChannel15Button, 4, 10, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout.addWidget(self.label_25)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.meditationPluginWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meditationPluginWidget.sizePolicy().hasHeightForWidth())
        self.meditationPluginWidget.setSizePolicy(sizePolicy)
        self.meditationPluginWidget.setObjectName(_fromUtf8("meditationPluginWidget"))
        self.gridLayout.addWidget(self.meditationPluginWidget, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.meditationCheckBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meditationCheckBox.sizePolicy().hasHeightForWidth())
        self.meditationCheckBox.setSizePolicy(sizePolicy)
        self.meditationCheckBox.setObjectName(_fromUtf8("meditationCheckBox"))
        self.horizontalLayout_5.addWidget(self.meditationCheckBox)
        self.meditationPluginComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meditationPluginComboBox.sizePolicy().hasHeightForWidth())
        self.meditationPluginComboBox.setSizePolicy(sizePolicy)
        self.meditationPluginComboBox.setObjectName(_fromUtf8("meditationPluginComboBox"))
        self.horizontalLayout_5.addWidget(self.meditationPluginComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.eyeBlinkCheckBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyeBlinkCheckBox.sizePolicy().hasHeightForWidth())
        self.eyeBlinkCheckBox.setSizePolicy(sizePolicy)
        self.eyeBlinkCheckBox.setObjectName(_fromUtf8("eyeBlinkCheckBox"))
        self.horizontalLayout_6.addWidget(self.eyeBlinkCheckBox)
        self.eyeBlinkPluginComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyeBlinkPluginComboBox.sizePolicy().hasHeightForWidth())
        self.eyeBlinkPluginComboBox.setSizePolicy(sizePolicy)
        self.eyeBlinkPluginComboBox.setObjectName(_fromUtf8("eyeBlinkPluginComboBox"))
        self.horizontalLayout_6.addWidget(self.eyeBlinkPluginComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.eyeBlinkPluginWidget = QtGui.QWidget(self.centralwidget)
        self.eyeBlinkPluginWidget.setObjectName(_fromUtf8("eyeBlinkPluginWidget"))
        self.gridLayout.addWidget(self.eyeBlinkPluginWidget, 5, 0, 1, 1)
        self.attentionPluginWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attentionPluginWidget.sizePolicy().hasHeightForWidth())
        self.attentionPluginWidget.setSizePolicy(sizePolicy)
        self.attentionPluginWidget.setObjectName(_fromUtf8("attentionPluginWidget"))
        self.gridLayout.addWidget(self.attentionPluginWidget, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.attentionCheckBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attentionCheckBox.sizePolicy().hasHeightForWidth())
        self.attentionCheckBox.setSizePolicy(sizePolicy)
        self.attentionCheckBox.setObjectName(_fromUtf8("attentionCheckBox"))
        self.horizontalLayout_4.addWidget(self.attentionCheckBox)
        self.attentionPluginComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attentionPluginComboBox.sizePolicy().hasHeightForWidth())
        self.attentionPluginComboBox.setSizePolicy(sizePolicy)
        self.attentionPluginComboBox.setObjectName(_fromUtf8("attentionPluginComboBox"))
        self.horizontalLayout_4.addWidget(self.attentionPluginComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuState = QtGui.QMenu(self.menubar)
        self.menuState.setObjectName(_fromUtf8("menuState"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_state = QtGui.QAction(MainWindow)
        self.actionSave_state.setObjectName(_fromUtf8("actionSave_state"))
        self.actionLoad_state = QtGui.QAction(MainWindow)
        self.actionLoad_state.setObjectName(_fromUtf8("actionLoad_state"))
        self.menuFile.addAction(self.actionQuit)
        self.menuState.addAction(self.actionLoad_state)
        self.menuState.addAction(self.actionSave_state)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuState.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.deviceComboBox, self.eyeBlinkSensitivity)
        MainWindow.setTabOrder(self.eyeBlinkSensitivity, self.lowerEyeBlinkFrequency)
        MainWindow.setTabOrder(self.lowerEyeBlinkFrequency, self.higherEyeBlinkFrequency)
        MainWindow.setTabOrder(self.higherEyeBlinkFrequency, self.rescanMidiButton)
        MainWindow.setTabOrder(self.rescanMidiButton, self.midiDevice0ComboBox)
        MainWindow.setTabOrder(self.midiDevice0ComboBox, self.midiDevice1ComboBox)
        MainWindow.setTabOrder(self.midiDevice1ComboBox, self.midiDevice2ComboBox)
        MainWindow.setTabOrder(self.midiDevice2ComboBox, self.midiDevice3ComboBox)
        MainWindow.setTabOrder(self.midiDevice3ComboBox, self.midiDevice4ComboBox)
        MainWindow.setTabOrder(self.midiDevice4ComboBox, self.midiDevice5ComboBox)
        MainWindow.setTabOrder(self.midiDevice5ComboBox, self.midiDevice6ComboBox)
        MainWindow.setTabOrder(self.midiDevice6ComboBox, self.midiDevice7ComboBox)
        MainWindow.setTabOrder(self.midiDevice7ComboBox, self.midiDevice8ComboBox)
        MainWindow.setTabOrder(self.midiDevice8ComboBox, self.midiDevice9ComboBox)
        MainWindow.setTabOrder(self.midiDevice9ComboBox, self.midiDevice10ComboBox)
        MainWindow.setTabOrder(self.midiDevice10ComboBox, self.midiDevice11ComboBox)
        MainWindow.setTabOrder(self.midiDevice11ComboBox, self.midiDevice12ComboBox)
        MainWindow.setTabOrder(self.midiDevice12ComboBox, self.midiDevice13ComboBox)
        MainWindow.setTabOrder(self.midiDevice13ComboBox, self.midiDevice14ComboBox)
        MainWindow.setTabOrder(self.midiDevice14ComboBox, self.midiDevice15ComboBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.startButton.setText(_translate("MainWindow", "Start/Stop", None))
        self.label.setText(_translate("MainWindow", "Mindwave device", None))
        self.deviceComboBox.setItemText(0, _translate("MainWindow", "/dev/rfcomm0", None))
        self.deviceComboBox.setItemText(1, _translate("MainWindow", "/dev/rfcomm1", None))
        self.deviceComboBox.setItemText(2, _translate("MainWindow", "/dev/rfcomm2", None))
        self.deviceComboBox.setItemText(3, _translate("MainWindow", "/dev/ttyUSB0", None))
        self.deviceComboBox.setItemText(4, _translate("MainWindow", "/dev/ttyUSB1", None))
        self.deviceComboBox.setItemText(5, _translate("MainWindow", "/dev/ttyUSB2", None))
        self.deviceComboBox.setItemText(6, _translate("MainWindow", "/dev/ttyS0", None))
        self.deviceComboBox.setItemText(7, _translate("MainWindow", "/dev/ttyS1", None))
        self.deviceComboBox.setItemText(8, _translate("MainWindow", "/dev/ttyS2", None))
        self.deviceComboBox.setItemText(9, _translate("MainWindow", "/dev/tty0", None))
        self.deviceComboBox.setItemText(10, _translate("MainWindow", "/dev/tty1", None))
        self.deviceComboBox.setItemText(11, _translate("MainWindow", "/dev/tty2", None))
        self.label_2.setText(_translate("MainWindow", "Eye blink sensitivity", None))
        self.eyeBlinkSensitivity.setText(_translate("MainWindow", "0.45", None))
        self.label_3.setText(_translate("MainWindow", "Lower Eye blink frequency  (Hz)", None))
        self.lowerEyeBlinkFrequency.setText(_translate("MainWindow", "5.0", None))
        self.label_4.setText(_translate("MainWindow", "Higher Eye blink frequency (Hz)", None))
        self.higherEyeBlinkFrequency.setText(_translate("MainWindow", "20.0", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Setup channel mapping</span></p></body></html>", None))
        self.rescanMidiButton.setText(_translate("MainWindow", "Rescan midi devices", None))
        self.label_14.setText(_translate("MainWindow", "MIDI chan 8", None))
        self.label_9.setText(_translate("MainWindow", "MIDI chan 0", None))
        self.label_11.setText(_translate("MainWindow", "MIDI chan 4", None))
        self.label_12.setText(_translate("MainWindow", "MIDI chan 5", None))
        self.label_24.setText(_translate("MainWindow", "MIDI chan 14", None))
        self.label_23.setText(_translate("MainWindow", "MIDI chan 15", None))
        self.label_13.setText(_translate("MainWindow", "MIDI chan 9", None))
        self.label_22.setText(_translate("MainWindow", "MIDI chan 10", None))
        self.label_21.setText(_translate("MainWindow", "MIDI chan 11", None))
        self.label_15.setText(_translate("MainWindow", "MIDI chan 12", None))
        self.label_16.setText(_translate("MainWindow", "MIDI chan 13", None))
        self.label_10.setText(_translate("MainWindow", "MIDI chan 1", None))
        self.label_19.setText(_translate("MainWindow", "MIDI chan 7", None))
        self.label_18.setText(_translate("MainWindow", "MIDI chan 3", None))
        self.label_17.setText(_translate("MainWindow", "MIDI chan 2", None))
        self.label_20.setText(_translate("MainWindow", "MIDI chan 6", None))
        self.resetChannel4Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel8Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel12Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel0Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel1Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel5Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel9Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel13Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel2Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel6Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel10Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel14Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel3Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel7Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel11Button.setText(_translate("MainWindow", "R", None))
        self.resetChannel15Button.setText(_translate("MainWindow", "R", None))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Setup event mapping</span></p></body></html>", None))
        self.meditationCheckBox.setText(_translate("MainWindow", "Meditation", None))
        self.eyeBlinkCheckBox.setText(_translate("MainWindow", "Eye blink", None))
        self.attentionCheckBox.setText(_translate("MainWindow", "Attention", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuState.setTitle(_translate("MainWindow", "State", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSave_state.setText(_translate("MainWindow", "Save state", None))
        self.actionLoad_state.setText(_translate("MainWindow", "Load state", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

